LINE_ACTION_TYPE_MESSAGE = 1
LINE_ACTION_TYPE_EMOTE = 2
LINE_ACTION_TYPE_JOIN = 3
LINE_ACTION_TYPE_PART = 4

LINE_ACTION_TYPE_CHOICES = (
    (LINE_ACTION_TYPE_MESSAGE, "Message"),
    (LINE_ACTION_TYPE_EMOTE, "Emote"),
    (LINE_ACTION_TYPE_JOIN, "Join"),
    (LINE_ACTION_TYPE_PART, "Part"),
)